### ISSUE TITLE
Error on running main.py

### ISSUE THREAD

**Issue by Pesktador** [Phype/telnet-iot-honeypot#1]
Cloned the project on my debian server and executed the main.py:

python main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from sampledb_client import Sampledb
  File "/var/www/html/telnet-iot-honeypot/sampledb_client.py", line 1, in <module>
    import client
  File "/var/www/html/telnet-iot-honeypot/client.py", line 5, in <module>
    from config import config
ImportError: No module named config

**Comment by Pesktador** [comment]
Alright nvm had to create the config.py , running fine now but it dosent create any samples.db?


I executed manually the sampledb.py to check if any errors appear since i dont see any while running the main.py 

Traceback (most recent call last):
  File "sampledb.py", line 14, in <module>
    from virustotal import Virustotal
ImportError: No module named virustotal

When i copy the virustotal.py from backend into the main dir 

Traceback (most recent call last):
  File "sampledb.py", line 14, in <module>
    from virustotal import Virustotal
  File "/var/www/html/telnet-iot-honeypot/virustotal.py", line 3, in <module>
    import db
  File "/var/www/html/telnet-iot-honeypot/db.py", line 46, in <module>
  File "/var/www/html/telnet-iot-honeypot/db.py", line 47, in DB
KeyError: 'sql'

**Comment by Phype** [comment]
Well, to be honest, I did not really think anyone would try to use this code.
In the last commits i tried to introduce a Client/Server Architekture for the honeypot,
where the Client would accept connections and download samples but the database
including all samples would be on the server.

These changes are not reflected in the documentation,
so i would recommend running the old application from commit
5caca711a12efb1b9c05ef1ff8eec68489a1e990.

To clear up this confusion, i "downgraded" the master tree to this commit,
keeping the client/server arch in a seperate branch. Cloning the master tree
should now result in an working application.

**Comment by Pesktador** [comment]
Thanks mate, love this project as i said.

Not sure why you think no one will use it, its so far the best honeypot i could find.

Some suggestions what could added:

- Create a List with the Top Connected IPs/IPs which loaded the most malware
Like 
IP - Connected x Times - URL to the malware

- Most used Username/Password List
- Some Country Charts?
