### ISSUE TITLE
Web-UI not showing data 

### ISSUE THREAD

**Issue by 3vangel1st** [Phype/telnet-iot-honeypot#10]
Hi, although I see the db filling with data and samples are downloaded, I see no data in my webinterface appearing. 

Also the generated admin account with random pwd from the config.yaml don't work when i want to login on the admin page of the web-interface.

Any suggestions on how to get these fixed please?

**Comment by f1r3walled** [comment]
Hi,
Show us your config.yaml file. How about permission on /var/www/html? What OS are you using?
I suffered a lot with this issue. Don't know exactly how it was fixed but after insist a lot, it worked to me.
Let me try to help!

**Comment by 3vangel1st** [comment]
config.yaml:

# This file was autogenerated
backend_user: "admin"
backend_pass: "HJQO7DNMULP2FD7LPHKGFO192OF6K***"
backend_salt: "0QCLM717BGMBRKF4GF51XNG8PBMAH***"

OS is Ubuntu

**Comment by timhux123** [comment]
I too am seeing the same issue. No data in the web interface and not able to log into the web interface using the credentials that were auto-generated. The permissions on /var/www/html are drwxr-xr-x www-data www-data. The OS is Ubuntu 16.04. The config.yaml file shows:

backend_user: "admin"
backend_pass: "22BUCCCPYSDMAHNHHS***"
backend_salt: "SBLTAFTFKUVRJ2VVPTPXW***"

**Comment by ulexec** [comment]
was this ever fixed?

**Comment by 3vangel1st** [comment]
no it wasn't - we tried many installations - different Linux versions etc..
