### ISSUE TITLE
Administration Area: Bad credentials

### ISSUE THREAD

**Issue by adamziaja** [Phype/telnet-iot-honeypot#13]
I have in config:
```
backend_user: "admin"
backend_pass: "pzBcmEC1gQ"
backend_salt: "GgZgZXf0PU"
```
_(passwords are not same as there)_
and this credentials don't work in `Administration Area`, I got `Bad credentials`, also from
`config.yaml`:
```
# This file was autogenerated

backend_user: "admin"
backend_pass: "..."
backend_salt: "..."
```
`backend_user` and `backend_pass` are not working... anyway there are not any informations on website so I guess it just don't use same config file because data is in database...

**Comment by jmb4444** [comment]
did you find a fix? casue im getting the same issue

**Comment by Phype** [comment]
The username/password in the config is only read at first start to create the admin user in the database. Changing the file afterwards will not have any effects, the username/password is than stored in the db (using an argon2 hash). If your database contains no important data, i would suggest to just scrap it and create a new one. 

Also Issue 15
