### ISSUE TITLE
No command get reply on default install

### ISSUE THREAD

**Issue by ameygat** [Phype/telnet-iot-honeypot#17]
I am using default config.yaml.

I run honeypot.py and backend.py.

When I connect to the IP address using netcat I get login after login no commands get any reply.

I am receving a lot of connections from multiple outside IP but no url or file download happening.

How to debug this  ? Is there any setting to enable Shell commands ?

**Comment by ameygat** [comment]
Anyone having same problem ?

**Comment by nicoloboatto** [comment]
If you are still interested, I've branched the project and pushed a fix for the issue.
