### ISSUE TITLE
All backend pages return a 404

### ISSUE THREAD

**Issue by Rammelkast** [Phype/telnet-iot-honeypot#20]
Failed to load resource: the server responded with a status of 404 (Not Found)
This is for all pages like /login/, /connection/ etc.

**Comment by Rammelkast** [comment]
I think this is related to #10

**Comment by Phype** [comment]
What do you mean with 404? Is there no page at all, or are the pages just empty? Please provide output of the backend.py server, there should be an exception in it. This could be an issue with the sqlite database, but i haven't managed to ultimately fix that. However, without log output, i can only guess what may be you problem.

**Comment by Rammelkast** [comment]
The tabs (latest urls, samples, connections) but also the login page makes a request to the server for data, but these requests give a 404.

Example (chrome console):
Failed to load resource: the server responded with a status of 404 (Not Found) for the URL /connection/statistics/per_country:1

**Comment by Rammelkast** [comment]
Fixed - changed host to 0.0.0.0 and opened firewall.
