### ISSUE TITLE
No data in web interface after installing Apache

### ISSUE THREAD

**Issue by timhux123** [Phype/telnet-iot-honeypot#21]
I installed apache using the commands in the Install steps:

sudo apt-get install apache2
cd telnet-iot-honeypot
cp -R html /var/www
sudo chown www-data:www-data /var/www -R

I restarted apache using "sudo service apache2 restart".
I'm still seeing data being populated in the web interface but still under port 5000 (http://127.0.0.1:5000) and not under port 80 (http://localhost).
Is there another configuration change needed so data is populated under the web interface served by apache?

**Comment by Phype** [comment]
You need to change html/apiurl.js to the url of the backend then (in the copy in /var/www, of course). If you are using apache to serve the frontend to other machines, remember that you need to make port 5000 accessible then or make apache do some reverse-proxying.

**Comment by timhux123** [comment]
Thanks for the update. I got it working by using your recommendations.
