### ISSUE TITLE
frontend all pages 404

### ISSUE THREAD

**Issue by hamdi-charef** [Phype/telnet-iot-honeypot#3]
After the server is started, this is displayed in the console:

```
Creating/Connecting to DB
DB Setup done
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Creating/Connecting to DB
DB Setup done
 * Debugger is active!
```

All the pages are not found 404, i  opened in my browser these urls:
http://server_ip:5000/html/index.html
http://server_ip:5000/index.html
http://server_ip:5000/sample.html
http://server_ip:5000

**Comment by doomedraven** [comment]
that isn't works in that way

install apache for example, move html folder to /var/www
change permission
change url to public ip in apiurl.js

and enjoy it :)

i will push a PR in a bit with some fixes and improvements
