### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by f1r3walled** [Phype/telnet-iot-honeypot#7]
Is anybody aware about the required dependencies?
I tried but everytime I have an installation issue, which requires an installation through pip install. I tried to run it through a Ubuntu 14.

Thank you!

**Comment by Phype** [comment]
Try the installation instructions provided by doomedraven. What is the problem with pip? I don't know if all the dependencies are actually packaged by ubuntu.

**Comment by f1r3walled** [comment]
It worked. Thank you!
